# Generated by Django 3.0.7 on 2021-01-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
